// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/access/[token]" | "/[locale]/admin" | "/[locale]/admin/articles" | "/[locale]/admin/articles/[id]/edit" | "/[locale]/admin/articles/new" | "/[locale]/admin/courses" | "/[locale]/admin/courses/[id]/edit" | "/[locale]/admin/courses/new" | "/[locale]/admin/login" | "/[locale]/admin/orders" | "/[locale]/admin/settings" | "/[locale]/admin/videos" | "/[locale]/admin/videos/[id]/edit" | "/[locale]/admin/videos/new" | "/[locale]/articles" | "/[locale]/articles/[slug]" | "/[locale]/cart" | "/[locale]/checkout/[slug]" | "/[locale]/courses" | "/[locale]/courses/[slug]" | "/[locale]/courses/[slug]/learn" | "/[locale]/instructors/[slug]" | "/[locale]/my-courses" | "/[locale]/shop" | "/[locale]/user/profile" | "/[locale]/videos" | "/[locale]/welcome"
type AppRouteHandlerRoutes = "/api/courses/by-slugs" | "/api/my-enrollments" | "/api/purchase" | "/api/qpay/check" | "/api/qpay/create" | "/api/stream/token" | "/api/videos/by-ids"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/access/[token]": { "locale": string; "token": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/articles": { "locale": string; }
  "/[locale]/admin/articles/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/admin/articles/new": { "locale": string; }
  "/[locale]/admin/courses": { "locale": string; }
  "/[locale]/admin/courses/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/admin/courses/new": { "locale": string; }
  "/[locale]/admin/login": { "locale": string; }
  "/[locale]/admin/orders": { "locale": string; }
  "/[locale]/admin/settings": { "locale": string; }
  "/[locale]/admin/videos": { "locale": string; }
  "/[locale]/admin/videos/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/admin/videos/new": { "locale": string; }
  "/[locale]/articles": { "locale": string; }
  "/[locale]/articles/[slug]": { "locale": string; "slug": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/checkout/[slug]": { "locale": string; "slug": string; }
  "/[locale]/courses": { "locale": string; }
  "/[locale]/courses/[slug]": { "locale": string; "slug": string; }
  "/[locale]/courses/[slug]/learn": { "locale": string; "slug": string; }
  "/[locale]/instructors/[slug]": { "locale": string; "slug": string; }
  "/[locale]/my-courses": { "locale": string; }
  "/[locale]/shop": { "locale": string; }
  "/[locale]/user/profile": { "locale": string; }
  "/[locale]/videos": { "locale": string; }
  "/[locale]/welcome": { "locale": string; }
  "/api/courses/by-slugs": {}
  "/api/my-enrollments": {}
  "/api/purchase": {}
  "/api/qpay/check": {}
  "/api/qpay/create": {}
  "/api/stream/token": {}
  "/api/videos/by-ids": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
