// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/access/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/access/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/access/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/articles/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/articles/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/articles/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/articles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/articles/new">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/articles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/articles">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/courses/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/courses/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/courses/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/courses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/courses/new">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/courses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/videos/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/videos/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/videos/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/videos/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/videos/new">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/videos/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/admin/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/videos">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/articles/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/articles/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/articles/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/articles">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/checkout/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/checkout/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/courses/[slug]/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/courses/[slug]/learn">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/courses/[slug]/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/courses/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/courses/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/courses/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/instructors/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/instructors/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/instructors/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/my-courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/my-courses">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/my-courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/user/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/user/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/user/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/videos">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/welcome">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/courses/by-slugs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/by-slugs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/courses/by-slugs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/my-enrollments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/my-enrollments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/my-enrollments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/purchase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase">> = Specific
  const handler = {} as typeof import("../../../src/app/api/purchase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/qpay/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qpay/check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/qpay/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/qpay/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qpay/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/qpay/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stream/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stream/token">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stream/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/videos/by-ids/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos/by-ids">> = Specific
  const handler = {} as typeof import("../../../src/app/api/videos/by-ids/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
